'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class [Default]

	''' <summary>
	''' form1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

	''' <summary>
	''' ProgressControl control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ProgressControl As Global.DevExpress.ExpressApp.Web.Controls.ProgressControl

	''' <summary>
	''' ApplicationTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ApplicationTitle As Global.System.Web.UI.WebControls.HyperLink

	''' <summary>
	''' InfoMessagesPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected InfoMessagesPanel As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' ViewTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewTitle As Global.System.Web.UI.WebControls.Table

	''' <summary>
	''' TableRow1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableRow1 As Global.System.Web.UI.WebControls.TableRow

	''' <summary>
	''' TableCell1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableCell1 As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' SearchActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected SearchActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' RecordsNavigationContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected RecordsNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' TableCell2 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TableCell2 As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' ViewImage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewImage As Global.System.Web.UI.WebControls.Image

	''' <summary>
	''' ViewCaption control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewCaption As Global.System.Web.UI.WebControls.Label

	''' <summary>
	''' ViewsHistoryNavigationContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewsHistoryNavigationContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationHistoryActionContainer

	''' <summary>
	''' NavigationBarActionContainer1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected NavigationBarActionContainer1 As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.NavigationBarActionContainer

	''' <summary>
	''' ContextObjectsCreationActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ContextObjectsCreationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' ListViewDataManagementActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ListViewDataManagementActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' TopRecordEditActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected TopRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' ViewPresentationActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewPresentationActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' ErrorInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ErrorInfo As Global.DevExpress.ExpressApp.Web.Templates.Controls.ErrorInfoControl

	''' <summary>
	''' Table1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Table1 As Global.System.Web.UI.WebControls.Table

	''' <summary>
	''' ViewSite control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ViewSite As Global.System.Web.UI.WebControls.TableCell

	''' <summary>
	''' BottomRecordEditActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected BottomRecordEditActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.HorizontalActionContainer

	''' <summary>
	''' Copyright control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected Copyright As Global.System.Web.UI.WebControls.Literal

	''' <summary>
	''' DiagnosticActionContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected DiagnosticActionContainer As Global.DevExpress.ExpressApp.Web.Templates.ActionContainers.WrappedHorizontalActionContainer

	''' <summary>
	''' LogoImage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected LogoImage As Global.System.Web.UI.WebControls.Image
End Class
